version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: majed
      POSTGRES_PASSWORD: 12345
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_boot_container
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: majed
      SPRING_DATASOURCE_PASSWORD: 12345

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react_container
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata: